ktor:
  application:
    modules:
      - net.kazugmx.acadule.ApplicationKt.module
  deployment:
    port: 8333
db:
  url: ${JDBC_URL:-jdbc:sqlite:data.db}
  user: ${JDBC_USER:-}
  password: ${JDBC_PASSWORD:-}
jwt:
  issuer: ${JWT_ISSUER:-acadule-backend}
  audience: "common users"
  realm: "acadule-backend"
  secret: ${JWT_SECRET:-secret } # test secret
